# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-15 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1024)),
                ('weight_ounces', models.IntegerField(default=0)),
                ('is_active', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
