# Generated by Django 3.0.6 on 2020-05-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
