# Generated by Django 3.0.6 on 2020-06-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_job_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='invite',
        ),
    ]
