# Generated by Django 3.0.6 on 2020-06-08 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_job_employee'),
        ('users', '0005_auto_20200609_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='job',
        ),
        migrations.AddField(
            model_name='invite',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='jobs.Job'),
        ),
    ]
