# Generated by Django 3.0.6 on 2020-06-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_remove_job_invite'),
        ('users', '0007_remove_invite_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='jobs.Job'),
        ),
    ]
