# Generated by Django 3.0.6 on 2020-06-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_remove_job_invite'),
        ('users', '0008_invite_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wish_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='wish_list', to='jobs.Job'),
        ),
    ]
